"""Contracts between components that must agree but are written down twice.

Nothing in the language checks any of these. They agreed when they were written
and drift silently afterwards -- which is exactly what happened to the emulator's
disassembler when the instruction frame went from 14 slots to 16, and to
tools/gen_words.py when FRAME changed. Each test here is a tripwire on a pair of
files that must say the same thing.
"""
import re
import sys

from compiler import compile_asm, FRAME as ASM_FRAME
from emulator import decode
from quattro.bus import Bus
from quattro.devices import GPU, Drive
from quattro.words import FRAME, WORD_QUARTERS, to_word, from_word

sys.path.insert(0, 'tools')


# --- the generated ALU vs its generator ---------------------------------

def test_words_py_matches_its_generator():
    """quattro/words.py says 'GENERATED by tools/gen_words.py -- do not edit by
    hand'. Once that stops being true, a regeneration silently reverts whatever
    was hand-edited in. It has already happened once."""
    from gen_words import generate_module
    generated = generate_module(WORD_QUARTERS)
    with open('quattro/words.py') as f:
        live = f.read()
    assert generated.strip() == live.strip(), (
        'quattro/words.py differs from tools/gen_words.py output -- someone '
        'hand-edited the generated file, or the generator drifted. '
        'Regenerate with: python tools/gen_words.py %d' % WORD_QUARTERS)


def test_frame_width_agrees():
    """One word IS one instruction frame -- that identity is what makes loading
    a program a straight copy in asm/boot.asm."""
    assert FRAME == WORD_QUARTERS == ASM_FRAME == 16


# --- the disassembler vs the assembler ----------------------------------

def test_disassembler_agrees_on_immediates():
    """emulator.py must unpack an immediate at the same width cpu.py does, or
    the debug panel reports a different number than the machine ran."""
    for value in (0, 1, 255, 256, 1000, 65535, 65536, 1048575):
        code, _ = compile_asm(f'LOAD R0, {value}\n')
        got = decode(code[0])
        assert got == f'LOAD R0, #{value}', f'LOAD R0, {value} disassembles as {got!r}'


def test_disassembler_agrees_on_jump_targets():
    for op in ('JMP', 'CALL'):
        for target in (0, 100, 4095, 4096, 5000, 65535):
            code, _ = compile_asm(f'{op} {target}\n')
            got = decode(code[0])
            assert got.split()[-1] == str(target), f'{op} {target} -> {got!r}'


def test_disassembler_agrees_on_branch_targets():
    for op, args in (('JZ', 'R1, '), ('JCMP', 'R1, '),
                     ('JEQ', 'R1, R2, '), ('JLT', 'R1, R2, ')):
        for target in (0, 4096, 65535):
            code, _ = compile_asm(f'{op} {args}{target}\n')
            got = decode(code[0])
            assert got.split()[-1] == str(target), f'{op} {target} -> {got!r}'


def test_disassembler_covers_every_instruction():
    """Every mnemonic the assembler emits must render as itself."""
    for src, want in (('LOAD R5, [R2]', 'LOAD R5, [R2]'),
                      ('STORE [R1], R3', 'STORE [R1], R3'),
                      ('COPY R7, R9', 'COPY R7, R9'),
                      ('HLT', 'HLT'), ('RET', 'RET')):
        code, _ = compile_asm(src + '\n')
        assert decode(code[0]) == want, f'{src} -> {decode(code[0])!r}'
    for src, head in (('ADD R1, R2', 'ADD'), ('SUB R1, R2', 'SUB'),
                      ('MUL R1, R2', 'MUL'), ('DIV R1, R2', 'DIV'),
                      ('MIN R1, R2', 'MIN'), ('MAX R1, R2', 'MAX'),
                      ('MOD R1, R2', 'MOD'), ('NOT R1', 'NOT')):
        code, _ = compile_asm(src + '\n')
        assert decode(code[0]).startswith(head), f'{src} -> {decode(code[0])!r}'


# --- the C headers vs the Python devices --------------------------------

def _defines(path, prefix):
    with open(path) as f:
        text = f.read()
    return {m.group(1): int(m.group(2))
            for m in re.finditer(rf'#define\s+({prefix}\w*)\s+(\d+)', text)}


def test_gpu_header_matches_the_device():
    """lib/gpu.h is what every C program on the machine believes about the GPU.
    Renumber a register in Python and C keeps poking the old address."""
    h = _defines('lib/gpu.h', 'GPU_')
    for name, reg in (('CMD', 'R_CMD'), ('X', 'R_X'), ('Y', 'R_Y'), ('W', 'R_W'),
                      ('H', 'R_H'), ('COLOR', 'R_COLOR'), ('ADDR', 'R_ADDR'),
                      ('X2', 'R_X2'), ('Y2', 'R_Y2'), ('MX', 'R_MX'),
                      ('MY', 'R_MY'), ('BTN', 'R_BTN'), ('STATUS', 'R_STATUS'),
                      ('CLICK', 'R_CLICK'), ('CLICKX', 'R_CLICKX'),
                      ('CLICKY', 'R_CLICKY')):
        want = Bus.GPU_BASE + getattr(GPU, reg)
        assert h[f'GPU_{name}'] == want, f'lib/gpu.h GPU_{name}={h[f"GPU_{name}"]}, device says {want}'
    assert h['GPU_WIDTH'] == GPU.W and h['GPU_HEIGHT'] == GPU.H


def test_gpu_header_window_fits_the_bus():
    h = _defines('lib/gpu.h', 'GPU_')
    ports = [v for k, v in h.items() if k not in ('GPU_WIDTH', 'GPU_HEIGHT')]
    assert min(ports) >= Bus.GPU_BASE and max(ports) <= Bus.GPU_TOP


def test_os_drive_registers_match_the_device():
    """c/os.cpp hardcodes the drive's ports; it is the OS, so if these drift the
    machine boots into a program that talks to the wrong device."""
    d = _defines('c/os.cpp', 'DRV_')
    for name, reg in (('CMD', 'R_CMD'), ('STATUS', 'R_STATUS'), ('NAME', 'R_NAME'),
                      ('BUF', 'R_BUF'), ('LEN', 'R_LEN'), ('POS', 'R_POS'),
                      ('RESULT', 'R_RESULT'), ('INDEX', 'R_INDEX')):
        want = Bus.DRV_BASE + getattr(Drive, reg)
        assert d[f'DRV_{name}'] == want, f'os.cpp DRV_{name}={d[f"DRV_{name}"]}, device says {want}'
    c = _defines('c/os.cpp', 'D_')
    for name, cmd in (('READ', 'C_READ'), ('WRITE', 'C_WRITE'), ('LIST', 'C_LIST')):
        assert c[f'D_{name}'] == getattr(Drive, cmd)


def test_boot_rom_ports_match_the_bus():
    """asm/boot.asm is the ROM: it hardcodes every port it touches. If one drifts
    the machine cannot boot at all."""
    with open('asm/boot.asm') as f:
        rom = f.read()
    for port, label in ((Bus.CODE_ADDR, 'CODE_ADDR'), (Bus.CODE_DATA, 'CODE_DATA'),
                        (Bus.DRV_BASE + Drive.R_CMD, 'DRV_CMD'),
                        (Bus.DRV_BASE + Drive.R_STATUS, 'DRV_STATUS'),
                        (Bus.DRV_BASE + Drive.R_NAME, 'DRV_NAME'),
                        (Bus.DRV_BASE + Drive.R_BUF, 'DRV_BUF')):
        assert re.search(rf'\b{port}\b', rom), (
            f'asm/boot.asm never mentions port {port} ({label}) -- the ROM and '
            f'the bus disagree')


# --- edge converters ----------------------------------------------------

def test_to_word_round_trips():
    for n in (0, 1, 3, 4, 255, 256, 65535, 65536, 1048575, 2**31, 4**16 - 1):
        assert from_word(to_word(n)) == n, n


def test_to_word_is_little_endian_base4():
    assert to_word(0)[:3] == (0, 0, 0)
    assert to_word(1)[:3] == (1, 0, 0)
    assert to_word(4)[:3] == (0, 1, 0)
    assert to_word(16)[:3] == (0, 0, 1)
    assert len(to_word(0)) == WORD_QUARTERS
