"""Words: 4 quaternary digits (little-endian), value 0..4**4-1.

GENERATED by tools/gen_words.py for WORD_QUARTERS = 4. Do not edit by hand;
change the width there and regenerate. to_word/from_word convert at the edges
only; WSEL/WOR/WNOT are the word mux gates; WADD..W_ALU are the word ALU, all
unrolled from the single-digit gates in gates.py (so purity_check still sees
pure gate logic). @ROM memoizes each pure block as a lookup ROM."""

from .gates import (ROM, ROM_BOUNDED, Adr4, EQ, MAX, MIN, NOT, HF_ADDER,
                    HF_SUBTRACT, HF_MULTIPLY)

WORD_QUARTERS = 4

# The instruction frame width (quaternary slots per instruction): one word is
# exactly one frame, which is what makes loading a program a straight copy.
FRAME = 4


# The bus re-derives the same handful of constant port numbers on every access
# (one per device decode line), so this is by far the hottest converter in the
# machine. Memoizing it is the same lookup-ROM trade @ROM makes for the gate
# blocks -- bounded, because unlike a gate block its input is a full 4-digit
# value, so an unbounded table would grow without limit.
@ROM_BOUNDED
def to_word(n):
    return tuple((n // (4 ** k)) % 4 for k in range(WORD_QUARTERS))


def from_word(w):
    return sum(v * (4 ** k) for k, v in enumerate(w))


ZERO_WORD = tuple(0 for _ in range(WORD_QUARTERS))
ONE_WORD = (1,) + tuple(0 for _ in range(WORD_QUARTERS - 1))


def FULL_ADD(a, b, cin):
    c1, s1 = HF_ADDER(a, b)
    c2, s = HF_ADDER(s1, cin)
    return MAX(c1, c2), s


def FULL_SUB(a, b, bin):
    br1, d1 = HF_SUBTRACT(a, b)
    br2, d = HF_SUBTRACT(d1, bin)
    return MAX(br1, br2), d


@ROM
def WSEL(sel, W):
    (w0, w1, w2, w3) = W
    return (MIN(sel, w0), MIN(sel, w1), MIN(sel, w2), MIN(sel, w3))


@ROM
def WOR(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    return (MAX(a0, b0), MAX(a1, b1), MAX(a2, b2), MAX(a3, b3))


@ROM
def WNOT(A):
    (a0, a1, a2, a3) = A
    return (NOT(a0), NOT(a1), NOT(a2), NOT(a3))


@ROM
def WADD(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    c1, s2 = FULL_ADD(a0, b0, 0)
    c3, s4 = FULL_ADD(a1, b1, c1)
    c5, s6 = FULL_ADD(a2, b2, c3)
    c7, s8 = FULL_ADD(a3, b3, c5)
    return c7, (s2, s4, s6, s8)


@ROM
def WSUB(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    b9, d10 = FULL_SUB(a0, b0, 0)
    b11, d12 = FULL_SUB(a1, b1, b9)
    b13, d14 = FULL_SUB(a2, b2, b11)
    b15, d16 = FULL_SUB(a3, b3, b13)
    return b15, (d10, d12, d14, d16)


@ROM
def WGE(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    b17, d18 = FULL_SUB(a0, b0, 0)
    b19, d20 = FULL_SUB(a1, b1, b17)
    b21, d22 = FULL_SUB(a2, b2, b19)
    b23, d24 = FULL_SUB(a3, b3, b21)
    g25 = EQ(b23, 0)
    return g25


@ROM
def WMUL(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    h26, l27 = HF_MULTIPLY(a0, b0)
    h28, l29 = HF_MULTIPLY(a1, b0)
    h30, l31 = HF_MULTIPLY(a2, b0)
    h32, l33 = HF_MULTIPLY(a3, b0)
    c34, o35 = HF_ADDER(l29, h26)
    _, k36 = HF_ADDER(h28, c34)
    c37, o38 = HF_ADDER(l31, k36)
    _, k39 = HF_ADDER(h30, c37)
    c40, o41 = HF_ADDER(l33, k39)
    mc42, ms43 = FULL_ADD(0, l27, 0)
    mc44, ms45 = FULL_ADD(0, o35, mc42)
    mc46, ms47 = FULL_ADD(0, o38, mc44)
    mc48, ms49 = FULL_ADD(0, o41, mc46)
    h50, l51 = HF_MULTIPLY(a0, b1)
    h52, l53 = HF_MULTIPLY(a1, b1)
    h54, l55 = HF_MULTIPLY(a2, b1)
    c56, o57 = HF_ADDER(l53, h50)
    _, k58 = HF_ADDER(h52, c56)
    c59, o60 = HF_ADDER(l55, k58)
    mc61, ms62 = FULL_ADD(ms45, l51, 0)
    mc63, ms64 = FULL_ADD(ms47, o57, mc61)
    mc65, ms66 = FULL_ADD(ms49, o60, mc63)
    h67, l68 = HF_MULTIPLY(a0, b2)
    h69, l70 = HF_MULTIPLY(a1, b2)
    c71, o72 = HF_ADDER(l70, h67)
    mc73, ms74 = FULL_ADD(ms64, l68, 0)
    mc75, ms76 = FULL_ADD(ms66, o72, mc73)
    h77, l78 = HF_MULTIPLY(a0, b3)
    mc79, ms80 = FULL_ADD(ms76, l78, 0)
    low = (ms43, ms62, ms74, ms80)
    return 0, low


@ROM
def WDIV(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    bnz = NOT(EQ(MAX(MAX(MAX(b0, b1), b2), b3), 0))
    b81, d82 = FULL_SUB(a3, b0, 0)
    b83, d84 = FULL_SUB(0, b1, b81)
    b85, d86 = FULL_SUB(0, b2, b83)
    b87, d88 = FULL_SUB(0, b3, b85)
    b89, d90 = FULL_SUB(0, 0, b87)
    b91, d92 = FULL_SUB(d82, b0, 0)
    b93, d94 = FULL_SUB(d84, b1, b91)
    b95, d96 = FULL_SUB(d86, b2, b93)
    b97, d98 = FULL_SUB(d88, b3, b95)
    b99, d100 = FULL_SUB(d90, 0, b97)
    b101, d102 = FULL_SUB(d92, b0, 0)
    b103, d104 = FULL_SUB(d94, b1, b101)
    b105, d106 = FULL_SUB(d96, b2, b103)
    b107, d108 = FULL_SUB(d98, b3, b105)
    b109, d110 = FULL_SUB(d100, 0, b107)
    e111 = EQ(b89, 0)
    e112 = EQ(b99, 0)
    e113 = EQ(b109, 0)
    q114 = MIN(bnz, MIN(e111, MAX(MIN(e112, MAX(MIN(e113, 3), MIN(NOT(e113), 2))), MIN(NOT(e112), 1))))
    q115 = EQ(q114, 0)
    q116 = EQ(q114, 1)
    q117 = EQ(q114, 2)
    q118 = EQ(q114, 3)
    r119 = MAX(MAX(MIN(q115, a3), MIN(q116, d82)), MAX(MIN(q117, d92), MIN(q118, d102)))
    r120 = MAX(MAX(MIN(q115, 0), MIN(q116, d84)), MAX(MIN(q117, d94), MIN(q118, d104)))
    r121 = MAX(MAX(MIN(q115, 0), MIN(q116, d86)), MAX(MIN(q117, d96), MIN(q118, d106)))
    r122 = MAX(MAX(MIN(q115, 0), MIN(q116, d88)), MAX(MIN(q117, d98), MIN(q118, d108)))
    r123 = MAX(MAX(MIN(q115, 0), MIN(q116, d90)), MAX(MIN(q117, d100), MIN(q118, d110)))
    b124, d125 = FULL_SUB(a2, b0, 0)
    b126, d127 = FULL_SUB(r119, b1, b124)
    b128, d129 = FULL_SUB(r120, b2, b126)
    b130, d131 = FULL_SUB(r121, b3, b128)
    b132, d133 = FULL_SUB(r122, 0, b130)
    b134, d135 = FULL_SUB(d125, b0, 0)
    b136, d137 = FULL_SUB(d127, b1, b134)
    b138, d139 = FULL_SUB(d129, b2, b136)
    b140, d141 = FULL_SUB(d131, b3, b138)
    b142, d143 = FULL_SUB(d133, 0, b140)
    b144, d145 = FULL_SUB(d135, b0, 0)
    b146, d147 = FULL_SUB(d137, b1, b144)
    b148, d149 = FULL_SUB(d139, b2, b146)
    b150, d151 = FULL_SUB(d141, b3, b148)
    b152, d153 = FULL_SUB(d143, 0, b150)
    e154 = EQ(b132, 0)
    e155 = EQ(b142, 0)
    e156 = EQ(b152, 0)
    q157 = MIN(bnz, MIN(e154, MAX(MIN(e155, MAX(MIN(e156, 3), MIN(NOT(e156), 2))), MIN(NOT(e155), 1))))
    q158 = EQ(q157, 0)
    q159 = EQ(q157, 1)
    q160 = EQ(q157, 2)
    q161 = EQ(q157, 3)
    r162 = MAX(MAX(MIN(q158, a2), MIN(q159, d125)), MAX(MIN(q160, d135), MIN(q161, d145)))
    r163 = MAX(MAX(MIN(q158, r119), MIN(q159, d127)), MAX(MIN(q160, d137), MIN(q161, d147)))
    r164 = MAX(MAX(MIN(q158, r120), MIN(q159, d129)), MAX(MIN(q160, d139), MIN(q161, d149)))
    r165 = MAX(MAX(MIN(q158, r121), MIN(q159, d131)), MAX(MIN(q160, d141), MIN(q161, d151)))
    r166 = MAX(MAX(MIN(q158, r122), MIN(q159, d133)), MAX(MIN(q160, d143), MIN(q161, d153)))
    b167, d168 = FULL_SUB(a1, b0, 0)
    b169, d170 = FULL_SUB(r162, b1, b167)
    b171, d172 = FULL_SUB(r163, b2, b169)
    b173, d174 = FULL_SUB(r164, b3, b171)
    b175, d176 = FULL_SUB(r165, 0, b173)
    b177, d178 = FULL_SUB(d168, b0, 0)
    b179, d180 = FULL_SUB(d170, b1, b177)
    b181, d182 = FULL_SUB(d172, b2, b179)
    b183, d184 = FULL_SUB(d174, b3, b181)
    b185, d186 = FULL_SUB(d176, 0, b183)
    b187, d188 = FULL_SUB(d178, b0, 0)
    b189, d190 = FULL_SUB(d180, b1, b187)
    b191, d192 = FULL_SUB(d182, b2, b189)
    b193, d194 = FULL_SUB(d184, b3, b191)
    b195, d196 = FULL_SUB(d186, 0, b193)
    e197 = EQ(b175, 0)
    e198 = EQ(b185, 0)
    e199 = EQ(b195, 0)
    q200 = MIN(bnz, MIN(e197, MAX(MIN(e198, MAX(MIN(e199, 3), MIN(NOT(e199), 2))), MIN(NOT(e198), 1))))
    q201 = EQ(q200, 0)
    q202 = EQ(q200, 1)
    q203 = EQ(q200, 2)
    q204 = EQ(q200, 3)
    r205 = MAX(MAX(MIN(q201, a1), MIN(q202, d168)), MAX(MIN(q203, d178), MIN(q204, d188)))
    r206 = MAX(MAX(MIN(q201, r162), MIN(q202, d170)), MAX(MIN(q203, d180), MIN(q204, d190)))
    r207 = MAX(MAX(MIN(q201, r163), MIN(q202, d172)), MAX(MIN(q203, d182), MIN(q204, d192)))
    r208 = MAX(MAX(MIN(q201, r164), MIN(q202, d174)), MAX(MIN(q203, d184), MIN(q204, d194)))
    r209 = MAX(MAX(MIN(q201, r165), MIN(q202, d176)), MAX(MIN(q203, d186), MIN(q204, d196)))
    b210, d211 = FULL_SUB(a0, b0, 0)
    b212, d213 = FULL_SUB(r205, b1, b210)
    b214, d215 = FULL_SUB(r206, b2, b212)
    b216, d217 = FULL_SUB(r207, b3, b214)
    b218, d219 = FULL_SUB(r208, 0, b216)
    b220, d221 = FULL_SUB(d211, b0, 0)
    b222, d223 = FULL_SUB(d213, b1, b220)
    b224, d225 = FULL_SUB(d215, b2, b222)
    b226, d227 = FULL_SUB(d217, b3, b224)
    b228, d229 = FULL_SUB(d219, 0, b226)
    b230, d231 = FULL_SUB(d221, b0, 0)
    b232, d233 = FULL_SUB(d223, b1, b230)
    b234, d235 = FULL_SUB(d225, b2, b232)
    b236, d237 = FULL_SUB(d227, b3, b234)
    b238, d239 = FULL_SUB(d229, 0, b236)
    e240 = EQ(b218, 0)
    e241 = EQ(b228, 0)
    e242 = EQ(b238, 0)
    q243 = MIN(bnz, MIN(e240, MAX(MIN(e241, MAX(MIN(e242, 3), MIN(NOT(e242), 2))), MIN(NOT(e241), 1))))
    q244 = EQ(q243, 0)
    q245 = EQ(q243, 1)
    q246 = EQ(q243, 2)
    q247 = EQ(q243, 3)
    r248 = MAX(MAX(MIN(q244, a0), MIN(q245, d211)), MAX(MIN(q246, d221), MIN(q247, d231)))
    r249 = MAX(MAX(MIN(q244, r205), MIN(q245, d213)), MAX(MIN(q246, d223), MIN(q247, d233)))
    r250 = MAX(MAX(MIN(q244, r206), MIN(q245, d215)), MAX(MIN(q246, d225), MIN(q247, d235)))
    r251 = MAX(MAX(MIN(q244, r207), MIN(q245, d217)), MAX(MIN(q246, d227), MIN(q247, d237)))
    r252 = MAX(MAX(MIN(q244, r208), MIN(q245, d219)), MAX(MIN(q246, d229), MIN(q247, d239)))
    Q = (q243, q200, q157, q114)
    R = (r248, r249, r250, r251)
    return R, Q


@ROM
def WMIN(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    b253, d254 = FULL_SUB(a0, b0, 0)
    b255, d256 = FULL_SUB(a1, b1, b253)
    b257, d258 = FULL_SUB(a2, b2, b255)
    b259, d260 = FULL_SUB(a3, b3, b257)
    g261 = EQ(b259, 0)
    gz = EQ(g261, 0)
    return (MAX(MIN(g261, b0), MIN(gz, a0)), MAX(MIN(g261, b1), MIN(gz, a1)), MAX(MIN(g261, b2), MIN(gz, a2)), MAX(MIN(g261, b3), MIN(gz, a3)))


@ROM
def WMAX(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    b262, d263 = FULL_SUB(a0, b0, 0)
    b264, d265 = FULL_SUB(a1, b1, b262)
    b266, d267 = FULL_SUB(a2, b2, b264)
    b268, d269 = FULL_SUB(a3, b3, b266)
    g270 = EQ(b268, 0)
    gz = EQ(g270, 0)
    return (MAX(MIN(g270, a0), MIN(gz, b0)), MAX(MIN(g270, a1), MIN(gz, b1)), MAX(MIN(g270, a2), MIN(gz, b2)), MAX(MIN(g270, a3), MIN(gz, b3)))


@ROM
def WMOD(A, B):
    cw, S = WADD(A, B)
    return S


@ROM
def WNZ(A):
    (a0, a1, a2, a3) = A
    return NOT(EQ(MAX(MAX(MAX(a0, a1), a2), a3), 0))


@ROM
def WEQ(A, B):
    (a0, a1, a2, a3) = A
    (b0, b1, b2, b3) = B
    return MIN(MIN(MIN(EQ(a0, b0), EQ(a1, b1)), EQ(a2, b2)), EQ(a3, b3))


@ROM
def W_ALU(InA, InB, Instr0, Instr1):
    """Word ALU: returns (flag_digit, result_word). Width-generic:
    every op runs; the class/sub-op decode lines select the result."""
    Aa, Bb, Cc, Dd = Adr4(Instr0, 3)
    A, B, C, D = Adr4(Instr1, Aa)
    A1, B1, C1, D1 = Adr4(Instr1, Bb)
    Cout, ADD = WADD(InA, InB)
    Borrow, SUBr = WSUB(InA, InB)
    Mov, MULr = WMUL(InA, InB)
    Rem, QUOT = WDIV(InA, InB)
    arith = WOR(WOR(WSEL(A, ADD), WSEL(B, SUBr)),
                WOR(WSEL(C, MULr), WSEL(D, QUOT)))
    (rm0, rm1, rm2, rm3) = Rem
    Xdiv = MIN(1, MAX(MAX(MAX(rm0, rm1), rm2), rm3))
    flag = MAX(MAX(MIN(A, Cout), MIN(B, Borrow)), MAX(MIN(C, Mov), MIN(D, Xdiv)))
    logic = WOR(WOR(WSEL(A1, WMIN(InA, InB)), WSEL(B1, WMAX(InA, InB))),
                WOR(WSEL(C1, WMOD(InA, InB)), WSEL(D1, WNOT(InA))))
    return flag, WOR(arith, logic)
